## Ejercicio 1
Importa la libreria de pandas. ¿Qué versión de la librería tienes?

In [8]:
import pandas as pd

pd.__version__

'1.3.3'

## Ejercicio 2
Lee el archivo CSV de la liga. Guarda el DataFrame en una variable llamada `df`. [Usa el método `read_csv` de `pandas`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html).

In [9]:
# fichero = "laliga.csv"
df = pd.read_csv("a/laliga.csv", sep = ',')
df

Unnamed: 0   season  division  round           localTeam    visitorTeam  \
0          26201  2005-06         1      1  Atletico de Bilbao  Real Sociedad   
1          26202  2005-06         1      1              Alaves      Barcelona   
2          26203  2005-06         1      1            Valencia          Betis   
3          26204  2005-06         1      1  Atletico de Madrid       Zaragoza   
4          26205  2005-06         1      1               Cadiz    Real Madrid   
...          ...      ...       ...    ...                 ...            ...   
4935       36680  2017-18         1     38          Villarreal    Real Madrid   
4936       36681  2017-18         1     38  Atletico de Bilbao        Espanol   
4937       36682  2017-18         1     38           Barcelona  Real Sociedad   
4938       36683  2017-18         1     38            Valencia      Deportivo   
4939       36684  2017-18         1     38  Atletico de Madrid          Eibar   

      localGoals  visitorGoals        date   timestamp  
0              3             0  27/08/2005  1125093600  
1              0             0  27/08/2005  1125093600  
2              1             0  27/08/2005  1125093600  
3              0             0  28/08/2005  1125180000  
4              1             2  28/08/2005  1125180000  
...          ...           ...         ...         ...  
4935           2             2  19/05/2018  1526680800  
4936           0             1  20/05/2018  1526767200  
4937           1             0  20/05/2018  1526767200  
4938           2             1  20/05/2018  1526767200  
4939           2             2  20/05/2018  1526767200  

[4940 rows x 10 columns]

## Ejercicio 3
Obtén por pantalla los 4 primero registros

In [10]:
df.head(4)

Unnamed: 0   season  division  round           localTeam    visitorTeam  \
0       26201  2005-06         1      1  Atletico de Bilbao  Real Sociedad   
1       26202  2005-06         1      1              Alaves      Barcelona   
2       26203  2005-06         1      1            Valencia          Betis   
3       26204  2005-06         1      1  Atletico de Madrid       Zaragoza   

   localGoals  visitorGoals        date   timestamp  
0           3             0  27/08/2005  1125093600  
1           0             0  27/08/2005  1125093600  
2           1             0  27/08/2005  1125093600  
3           0             0  28/08/2005  1125180000

In [13]:
df[0:4]

Unnamed: 0   season  division  round           localTeam    visitorTeam  \
0       26201  2005-06         1      1  Atletico de Bilbao  Real Sociedad   
1       26202  2005-06         1      1              Alaves      Barcelona   
2       26203  2005-06         1      1            Valencia          Betis   
3       26204  2005-06         1      1  Atletico de Madrid       Zaragoza   

   localGoals  visitorGoals        date   timestamp  
0           3             0  27/08/2005  1125093600  
1           0             0  27/08/2005  1125093600  
2           1             0  27/08/2005  1125093600  
3           0             0  28/08/2005  1125180000

In [17]:
df_4 = pd.read_csv("a/laliga.csv", nrows = 4, sep = ',')
print(df_4)

   Unnamed: 0   season  division  round           localTeam    visitorTeam  \
0       26201  2005-06         1      1  Atletico de Bilbao  Real Sociedad   
1       26202  2005-06         1      1              Alaves      Barcelona   
2       26203  2005-06         1      1            Valencia          Betis   
3       26204  2005-06         1      1  Atletico de Madrid       Zaragoza   

   localGoals  visitorGoals        date   timestamp  
0           3             0  27/08/2005  1125093600  
1           0             0  27/08/2005  1125093600  
2           1             0  27/08/2005  1125093600  
3           0             0  28/08/2005  1125180000  


In [19]:
df.iloc[0:4]

Unnamed: 0   season  division  round           localTeam    visitorTeam  \
0       26201  2005-06         1      1  Atletico de Bilbao  Real Sociedad   
1       26202  2005-06         1      1              Alaves      Barcelona   
2       26203  2005-06         1      1            Valencia          Betis   
3       26204  2005-06         1      1  Atletico de Madrid       Zaragoza   

   localGoals  visitorGoals        date   timestamp  
0           3             0  27/08/2005  1125093600  
1           0             0  27/08/2005  1125093600  
2           1             0  27/08/2005  1125093600  
3           0             0  28/08/2005  1125180000

In [20]:
df.loc[0:3]

Unnamed: 0   season  division  round           localTeam    visitorTeam  \
0       26201  2005-06         1      1  Atletico de Bilbao  Real Sociedad   
1       26202  2005-06         1      1              Alaves      Barcelona   
2       26203  2005-06         1      1            Valencia          Betis   
3       26204  2005-06         1      1  Atletico de Madrid       Zaragoza   

   localGoals  visitorGoals        date   timestamp  
0           3             0  27/08/2005  1125093600  
1           0             0  27/08/2005  1125093600  
2           1             0  27/08/2005  1125093600  
3           0             0  28/08/2005  1125180000

## Ejercicio 4
Obtén en un array de `numpy` todos los valores del DataFrame

In [21]:
df.values

array([[26201, '2005-06', 1, ..., 0, '27/08/2005', 1125093600],
       [26202, '2005-06', 1, ..., 0, '27/08/2005', 1125093600],
       [26203, '2005-06', 1, ..., 0, '27/08/2005', 1125093600],
       ...,
       [36682, '2017-18', 1, ..., 0, '20/05/2018', 1526767200],
       [36683, '2017-18', 1, ..., 1, '20/05/2018', 1526767200],
       [36684, '2017-18', 1, ..., 2, '20/05/2018', 1526767200]],
      dtype=object)

In [22]:
df.to_numpy()

array([[26201, '2005-06', 1, ..., 0, '27/08/2005', 1125093600],
       [26202, '2005-06', 1, ..., 0, '27/08/2005', 1125093600],
       [26203, '2005-06', 1, ..., 0, '27/08/2005', 1125093600],
       ...,
       [36682, '2017-18', 1, ..., 0, '20/05/2018', 1526767200],
       [36683, '2017-18', 1, ..., 1, '20/05/2018', 1526767200],
       [36684, '2017-18', 1, ..., 2, '20/05/2018', 1526767200]],
      dtype=object)

## Ejercicio 5
¿Cuáles son las columnas de `df`?

In [23]:
df.columns

Index(['Unnamed: 0', 'season', 'division', 'round', 'localTeam', 'visitorTeam',
       'localGoals', 'visitorGoals', 'date', 'timestamp'],
      dtype='object')

In [25]:
# pd.DataFrame(data=None, columns = [df])

Empty DataFrame
Columns: [(Unnamed: 0,), (season,), (division,), (round,), (localTeam,), (visitorTeam,), (localGoals,), (visitorGoals,), (date,), (timestamp,)]
Index: []

## Ejercicio 6
Crea un `Series` con la [población de Madrid, Galicia, Murcia y Andalucía](https://es.wikipedia.org/wiki/Anexo:Comunidades_y_ciudades_aut%C3%B3nomas_de_Espa%C3%B1a). Llamalo `poblacion`. Créalo de dos maneras diferentes.

Madrid: 6685471

Galicia: 2698764

Murcia: 1494442

Andalucía: 8446561


In [26]:
poblacion = pd.Series({"Madrid": 6685471, "Galicia": 2698764, "Murcia": 1494442, "Andalucia": 8446561})
poblacion

Madrid       6685471
Galicia      2698764
Murcia       1494442
Andalucia    8446561
dtype: int64

In [27]:
poblacion = pd.Series([6685471, 2698764, 1494442, 8446561], index = ["Madrid", "Galicia", "Murcia", "Andalucia"])
poblacion

Madrid       6685471
Galicia      2698764
Murcia       1494442
Andalucia    8446561
dtype: int64

## Ejercicio 7
Obtén un array de `numpy` con los valores del `Series`.

Saca también sus índices, y los valores de sus índices.

In [29]:
print(poblacion.values)
print(poblacion.index)

[6685471 2698764 1494442 8446561]
Index(['Madrid', 'Galicia', 'Murcia', 'Andalucia'], dtype='object')


## Ejercicio 8
1. ¿Qué población hay en el primer elemento del `Series`?
2. ¿Qué población hay en Galicia?
3. Imprime por pantalla las poblaciones de Galicia, Andalucía y las comunidades autónomas que se encuentren entre ambas, dentro del `Series`.
4. Comprueba con un output booleano que `Galicia` se encuentra entre los índices del `Index`.
5. Realiza los apartados 1,2,3 pero esta vez de una manera diferente.

In [31]:
print(poblacion.loc['Madrid'])

6685471


In [32]:
print(poblacion[0])

6685471


In [33]:
print(poblacion.iloc[0])

6685471


In [34]:
print(poblacion['Galicia'])

2698764


In [52]:
print(poblacion['Galicia': 'Andalucia'])
print(poblacion.iloc[1:4])
print(poblacion.loc['Galicia': 'Andalucia'])

Galicia      2698764
Murcia       1494442
Andalucia    8446561
dtype: int64
Galicia      2698764
Murcia       1494442
Andalucia    8446561
dtype: int64
Galicia      2698764
Murcia       1494442
Andalucia    8446561
dtype: int64


In [49]:
print('Galicia' in poblacion)
print('Galicia' in poblacion.index)

False
True


In [47]:
if poblacion['Galicia']:
    print(True)

True


In [39]:
type(poblacion)

pandas.core.series.Series

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4940 entries, 0 to 4939
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Unnamed: 0    4940 non-null   int64 
 1   season        4940 non-null   object
 2   division      4940 non-null   int64 
 3   round         4940 non-null   int64 
 4   localTeam     4940 non-null   object
 5   visitorTeam   4940 non-null   object
 6   localGoals    4940 non-null   int64 
 7   visitorGoals  4940 non-null   int64 
 8   date          4940 non-null   object
 9   timestamp     4940 non-null   int64 
dtypes: int64(6), object(4)
memory usage: 386.1+ KB


In [44]:
df.describe()

Unnamed: 0  division        round   localGoals  visitorGoals  \
count   4940.000000    4940.0  4940.000000  4940.000000   4940.000000   
mean   31442.500000       1.0    19.500000     1.579960      1.143320   
std     3152.703808       0.0    10.966966     1.356142      1.150766   
min    26201.000000       1.0     1.000000     0.000000      0.000000   
25%    28821.750000       1.0    10.000000     1.000000      0.000000   
50%    31442.500000       1.0    19.500000     1.000000      1.000000   
75%    34063.250000       1.0    29.000000     2.000000      2.000000   
max    36684.000000       1.0    38.000000    10.000000      8.000000   

          timestamp  
count  4.940000e+03  
mean   1.326497e+09  
std    1.181155e+08  
min    1.125094e+09  
25%    1.226185e+09  
50%    1.327489e+09  
75%    1.428120e+09  
max    1.526767e+09

## Ejercicio 9
A partir de las comunidades autónomas anteriores, crea un `Series` con [la tasa de paro](https://es.statista.com/estadisticas/941646/prevision-de-la-tasa-de-paro-por-comunidad-autonoma-espana/) en dichas comunidades autónomas.

Con la tasa de paro y las poblaciones, crea un DataFrame de pandas. Llámalo `data`.

Tasas de paro

Madrid: 9.99

Galicia: 11.74

Murcia: 16.08

Andalucía: 20.8

In [57]:
paro = pd.Series({'Madrid': 9.99, "Galicia": 11.74, "Murcia":16.08, "Andalucia":20.8})
paro

Madrid        9.99
Galicia      11.74
Murcia       16.08
Andalucia    20.80
dtype: float64

In [58]:
type(poblacion)

pandas.core.series.Series

In [59]:
data = pd.DataFrame({"poblacion":poblacion, "paro": paro})
data

poblacion   paro
Madrid       6685471   9.99
Galicia      2698764  11.74
Murcia       1494442  16.08
Andalucia    8446561  20.80

## Ejercicio 10
Imprime por pantalla la población, y la tasa de paro. Por separado

## Ejercicio 11
Crea un nuevo Data Frame (`data2`), que sea igual que `data`, pero con una nueva columna, que lleve [la superficie de las Comunidades Autónomas](https://es.wikipedia.org/wiki/Anexo:Comunidades_y_ciudades_aut%C3%B3nomas_de_Espa%C3%B1a).

Madrid: 8028

Galicia: 29575

Murcia: 11314

Andalucía: 87599

## Ejercicio 12
Calcula en una nueva columna la densidad de población (hab/km^2)